---

- name: "Create project for workload {{ocp_project}}"
  shell: "oc new-project {{ocp_project}}"

- name: Make sure we go back to default project
  shell: "oc project default"


### LimitRange
###     RH-SSO template only allows for specifying RAM for SSO deployment config.
###     Limits and requests for mysql dc are not defined and subsequently are subject to default settings in a limitrange
- name: Ensure {{work_dir}} exists
  file:
    path: "{{work_dir}}"
    state: directory

- name: Delete default limitrange
  shell: |
    oc delete limitrange {{ocp_project}}-core-resource-limits -n {{ocp_project}}
  ignore_errors: true

- name: Create a new limitrange
  template:
    src: templates/limitrange.yaml
    dest: "{{work_dir}}/limitrange.yaml"
- shell: |
    oc create -f {{work_dir}}/limitrange.yaml -n {{ocp_project}}

- name: Annotate the empty project as requested by user
  shell: "oc annotate namespace {{ocp_project}} openshift.io/requester={{admin_username}} --overwrite"


### RH-SSO Setup

- name: Create SSO Service Account
  shell: "oc create serviceaccount sso-service-account -n {{ ocp_project }}"

- name: Give service account access to Lab Infra project
  shell: "oc policy add-role-to-user view system:serviceaccount:{{ ocp_project }}:sso-service-account"

- name: Create RHSSO app
  shell: |
       oc new-app \
           --template={{ rhsso_template_name }} \
           --param=SSO_ADMIN_USERNAME={{ SSO_SITE_ADMIN_USERNAME }} \
           --param=SSO_ADMIN_PASSWORD={{ SSO_SITE_ADMIN_PASSWORD }} \
           --param=MEMORY_LIMIT=2Gi \
           -n {{ ocp_project }} \
           > {{ work_dir }}/sso_provision.txt

- pause:
    seconds: 5

- include_tasks: wait_for_deploy.yml
  vars:
    pod_to_wait:
      - sso
      - sso-mysql


### Project finalization
  
- name: Give admin_username access to ocp_project; user = {{admin_username}}
  shell: "oc policy add-role-to-user admin {{admin_username}} -n {{ocp_project}}"

- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete
